#!/usr/bin/env python3
"""
Download script for steacher - run this on the login server
Downloads the model and prepares the environment for HPC cluster execution
"""

import os
import sys
from pathlib import Path
from huggingface_hub import snapshot_download

# Configuration
BASE_DIR = Path.home() / "scratch" / "tommy2130"
LARGE_MODEL_NAME = "simplescaling/s1.1-7B"

def main():
    print("Setting up steacher environment...")
    print(f"Base directory: {BASE_DIR}")
    
    # Create base directory if it doesn't exist
    BASE_DIR.mkdir(parents=True, exist_ok=True)
    
    # Define checkpoint path
    checkpoint_dir = BASE_DIR / "models" / "s1.1-7B"
    
    print(f"Downloading model: {LARGE_MODEL_NAME}")
    print(f"Saving to: {checkpoint_dir}")
    
    try:
        # Download the model
        downloaded_path = snapshot_download(
            repo_id=LARGE_MODEL_NAME,
            local_dir=str(checkpoint_dir),
            local_dir_use_symlinks=False,  # Use actual files instead of symlinks for HPC
        )
        
        print(f"✅ Model downloaded successfully to: {downloaded_path}")
        
        # Create a simple config file with paths
        config_file = BASE_DIR / "steacher_config.py"
        with open(config_file, 'w') as f:
            f.write(f'# Steacher configuration file\n')
            f.write(f'# Generated by steacher_download.py\n\n')
            f.write(f'LARGE_CHECKPOINT_PATH = "{checkpoint_dir}"\n')
            f.write(f'BASE_DIR = "{BASE_DIR}"\n')
        
        print(f"✅ Configuration file created: {config_file}")
        
        # Create directories for data and logs
        (BASE_DIR / "data").mkdir(exist_ok=True)
        (BASE_DIR / "logs").mkdir(exist_ok=True)
        
        print(f"✅ Created data and logs directories")
        
        print("\n" + "="*60)
        print("DOWNLOAD COMPLETE!")
        print("="*60)
        print(f"Model location: {checkpoint_dir}")
        print(f"Config file: {config_file}")
        print(f"Base directory: {BASE_DIR}")
        print("\nYou can now run steacher_indices.py on compute nodes.")
        print("Make sure to copy your database files to the data directory:")
        print(f"  cp your_dataset.db {BASE_DIR}/data/")
        
    except Exception as e:
        print(f"❌ Error downloading model: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
